version: 2
updates:
    - package-ecosystem: 'bun'
      directories:
          - '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '09:00'
          timezone: 'America/Sao_Paulo'
      open-pull-requests-limit: 3
      groups:
          all-dependencies:
              applies-to: 'version-updates'
              patterns:
                  - '*'
          security-dependencies:
              applies-to: 'security-updates'
              patterns:
                  - '*'
